project:
  type: website

website:
  title: "Notes on Quarto 1.7 performance work"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - about.qmd
      - summary.qmd

format:
  html:
    theme:
      - brand
    css: styles.css



